<?php

namespace AppBundle\Entity;

/**
 * ObjectifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifRepository extends \Doctrine\ORM\EntityRepository
{
}
